"""Fix Event and EventTag relationships

Revision ID: 060730f636d3
Revises: 
Create Date: 2024-09-28 21:04:37.179877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060730f636d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(), nullable=False),
    sa.Column('Host', sa.String(), nullable=False),
    sa.Column('Location', sa.String(), nullable=False),
    sa.Column('Description', sa.String(), nullable=False),
    sa.Column('Date', sa.DateTime(), nullable=False),
    sa.Column('Picture', sa.String(), nullable=False),
    sa.Column('WebOrig', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tags')
    op.drop_table('Events')
    with op.batch_alter_table('event_tag_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'])
        batch_op.create_foreign_key(None, 'eventTags', ['tag_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_tag_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tags', ['tag_id'], ['id'])
        batch_op.create_foreign_key(None, 'Events', ['event_id'], ['id'])

    op.create_table('Events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Title', sa.VARCHAR(), nullable=False),
    sa.Column('Host', sa.VARCHAR(), nullable=False),
    sa.Column('Location', sa.VARCHAR(), nullable=False),
    sa.Column('Description', sa.VARCHAR(), nullable=False),
    sa.Column('Date', sa.DATETIME(), nullable=False),
    sa.Column('Picture', sa.VARCHAR(), nullable=False),
    sa.Column('WebOrig', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('events')
    # ### end Alembic commands ###
